# Generated by Django 5.1.7 on 2025-03-26 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COOKING', 'Cooking'), ('MASONRY', 'Masonry'), ('CLASS', 'Class')], max_length=20, verbose_name='Favor type')),
                ('description', models.TextField(verbose_name='Description')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Favor',
                'verbose_name_plural': 'Favors',
            },
        ),
    ]
