# Generated by Django 5.1.7 on 2025-03-26 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_favors', to=settings.AUTH_USER_MODEL, verbose_name='Assigned user'),
        ),
        migrations.AddField(
            model_name='favor',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_favors', to=settings.AUTH_USER_MODEL, verbose_name='Favor creator'),
        ),
    ]
