# Generated by Django 5.2 on 2025-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favor', '0003_favor_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
