# Generated by Django 5.2 on 2025-04-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('favor', '0004_favor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='favor',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favors', to='district.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='favor',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='favor',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
