# Generated by Django 5.2 on 2025-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favor', '0005_favor_district_alter_favor_points_alter_favor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favor',
            name='type',
            field=models.CharField(choices=[('HOME', 'Hogar'), ('TRANSPORT', 'Transporte'), ('PETS', 'Mascotas'), ('TECH', 'Tecnología'), ('CLASS', 'Clases'), ('COOKING', 'Cocina'), ('PLUMBING', 'Fontanería'), ('CARPENTRY', 'Carpintería'), ('ERRANDS', 'Recados'), ('SHOPPING', 'Compra')], max_length=20, verbose_name='Favor type'),
        ),
    ]
