# Generated by Django 5.1.7 on 2025-03-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_rename_points_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
    ]
