export { default as BoardPage } from './BoardPage';
export { default as TransactionsPage } from './TransactionsPage';
export { MyFavorsPage } from './MyFavorsPage';
export { default as SignUpForm } from './SignUpForm';
export { default as SignInForm } from './SignInForm';
export { default as HomeLoginPage } from './Home/HomeLoginPage';
export { default as HomeUnlogPage } from './Home/HomeUnlog'; 
export { default as ComoFunciona } from './ComoFunciona';
export { default as SistemaPuntos } from './SistemaPuntos';
export { default as Seguridad } from './Seguridad';
export { default as HistoriasExito } from './HistoriasExito';
export { default as CentroAyuda } from './CentroAyuda';
export { default as NormasComunidad } from './NormasComunidad';
export { default as PoliticaPrivacidad } from './PoliticaPrivacidad';
export { default as Contacto } from './Contacto';