# Generated by Django 5.1.7 on 2025-03-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SPEND', 'Spend'), ('EARN', 'Earn')], max_length=5)),
                ('amount', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('favor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='favor.favor')),
            ],
        ),
    ]
